spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/cinema
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format_sql: true
project:
  poster: posters
server:
  port: 8091
base:
  url: "http://localhost:8091"